AWSTemplateFormatVersion: '2010-09-09'
Description: Launch EC2 instance with Spring Boot App

Parameters:
  KeyName:
    Type: String
    Description: Name of an existing EC2 KeyPair to SSH
  AppBucket:
    Type: String
    Description: S3 bucket containing the Spring Boot JAR
  JarFile:
    Type: String
    Description: Name of the Spring Boot JAR file

Resources:
  MyEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      KeyName: !Ref KeyName
      ImageId: ami-0c02fb55956c7d316  # Amazon Linux 2 (region-specific)
      Tags:
        - Key: Name
          Value: SpringBootAppInstance
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          yum install -y java-1.8.0-openjdk wget
          aws s3 cp s3://${AppBucket}/${JarFile} /home/ec2-user/app.jar
          java -jar /home/ec2-user/app.jar > /home/ec2-user/app.log 2>&1 &
