AWSTemplateFormatVersion: '2010-09-09'
Description: Launch a basic EC2 instance

Parameters:
  KeyName:
    Description: Name of an existing EC2 KeyPair to enable SSH access
    Type: String
  InstanceType:
    Description: EC2 instance type
    Type: String
    Default: t2.micro
  AmiId:
    Description: AMI ID for the EC2 instance
    Type: AWS::EC2::Image::Id

Resources:
  MyEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: !Ref InstanceType
      KeyName: !Ref KeyName
      ImageId: !Ref AmiId
      Tags:
        - Key: Name
          Value: MyJenkinsCreatedEC2
      SecurityGroups:
        - !Ref MySecurityGroup

  MySecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Enable SSH access
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
